[build]
  functions = "netlify/functions"
  publish = "public" # Apenas se você tiver arquivos estáticos, caso contrário remova

[[redirects]]
  # Redireciona apenas as requisições que precisam ser tratadas pela função serverless
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

  # Deixe páginas estáticas (HTML, CSS, JS) acessíveis sem redirecionamento
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[edge_functions]]
  function = "myEdgeFunction" # Substitua pelo nome real da sua função
  path = "/test"
