[build]
  functions = "netlify/functions"
  publish = "public" # Apenas se você tiver arquivos estáticos. Caso contrário, remova.

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200


[[edge_functions]]
function = "FUNCTION-NAME"
path = "/test"